-- Loads base16 colors from the stylix cache file generated by Nix/Home Manager.
-- The file is a symlink into the Nix store and is always current after a rebuild.
-- Falls back to default placeholder colors if the file is missing or unreadable.

-- Fallback colors used when the stylix cache is unavailable.
local defaults = {
  base00 = "1e1e2e",
  base01 = "181825",
  base02 = "313244",
  base03 = "45475a",
  base04 = "585b70",
  base05 = "cdd6f4",
  base06 = "f5e0dc",
  base07 = "b4befe",
  base08 = "f38ba8",
  base09 = "fab387",
  base0A = "f9e2af",
  base0B = "a6e3a1",
  base0C = "94e2d5",
  base0D = "89b4fa",
  base0E = "cba6f7",
  base0F = "f2cdcd",
}

local colors = {}

-- Attempt to load colors from ~/.cache/stylix/colors.json.
-- The file format is: {"base00":"#rrggbb", "base01":"#rrggbb", ...}
local path = os.getenv("HOME") .. "/.cache/stylix/colors.json"
local f = io.open(path, "r")

if f then
  local content = f:read("*a")
  f:close()
  for key, value in content:gmatch('"(base%x%x)":"#(%x+)"') do
    colors[key] = value
  end
else
  -- stylix cache not found, using fallback defaults
  colors = defaults
end

-- Ensure all keys are present even if the file was partially parsed.
for key, value in pairs(defaults) do
  if not colors[key] then
    colors[key] = value
  end
end

return colors
